# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ItemV8.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ItemV8.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cItemV8.proto\"/\n\x0cKeyReference\x12\x12\n\nwrappedKey\x18\x01 \x02(\x0c\x12\x0b\n\x03rfu\x18\x02 \x01(\x05\"]\n\nSecretData\x12\x15\n\rencryptedData\x18\x01 \x02(\x0c\x12#\n\x0ckeyReference\x18\x02 \x02(\x0b\x32\r.KeyReference\x12\x13\n\x0btamperCheck\x18\x03 \x02(\t\"a\n\x11\x45ncryptedMetadata\x12\x19\n\x11\x65ncryptedMetadata\x18\x01 \x02(\x0c\x12\x1c\n\x14\x65ncryptedMetadataKey\x18\x02 \x02(\x0c\x12\x13\n\x0btamperCheck\x18\x03 \x02(\t\"\x94\x02\n\x06ItemV8\x12\x1f\n\nsecretData\x18\x01 \x02(\x0b\x32\x0b.SecretData\x12-\n\x11\x65ncryptedMetadata\x18\x02 \x02(\x0b\x32\x12.EncryptedMetadata\x12\x31\n\x08keyclass\x18\x03 \x02(\x0e\x32\x10.ItemV8.Keyclass:\rKEYCLASS_AKPU\"\x86\x01\n\x08Keyclass\x12\x0f\n\x0bKEYCLASS_AK\x10\x06\x12\x0f\n\x0bKEYCLASS_CK\x10\x07\x12\x0f\n\x0bKEYCLASS_DK\x10\x08\x12\x10\n\x0cKEYCLASS_AKU\x10\t\x12\x10\n\x0cKEYCLASS_CKU\x10\n\x12\x10\n\x0cKEYCLASS_DKU\x10\x0b\x12\x11\n\rKEYCLASS_AKPU\x10\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ITEMV8_KEYCLASS = _descriptor.EnumDescriptor(
  name='Keyclass',
  full_name='ItemV8.Keyclass',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_AK', index=0, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_CK', index=1, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_DK', index=2, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_AKU', index=3, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_CKU', index=4, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_DKU', index=5, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEYCLASS_AKPU', index=6, number=12,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=402,
  serialized_end=536,
)
_sym_db.RegisterEnumDescriptor(_ITEMV8_KEYCLASS)


_KEYREFERENCE = _descriptor.Descriptor(
  name='KeyReference',
  full_name='KeyReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wrappedKey', full_name='KeyReference.wrappedKey', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rfu', full_name='KeyReference.rfu', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=63,
)


_SECRETDATA = _descriptor.Descriptor(
  name='SecretData',
  full_name='SecretData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encryptedData', full_name='SecretData.encryptedData', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keyReference', full_name='SecretData.keyReference', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tamperCheck', full_name='SecretData.tamperCheck', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=158,
)


_ENCRYPTEDMETADATA = _descriptor.Descriptor(
  name='EncryptedMetadata',
  full_name='EncryptedMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encryptedMetadata', full_name='EncryptedMetadata.encryptedMetadata', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encryptedMetadataKey', full_name='EncryptedMetadata.encryptedMetadataKey', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tamperCheck', full_name='EncryptedMetadata.tamperCheck', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=257,
)


_ITEMV8 = _descriptor.Descriptor(
  name='ItemV8',
  full_name='ItemV8',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='secretData', full_name='ItemV8.secretData', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encryptedMetadata', full_name='ItemV8.encryptedMetadata', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keyclass', full_name='ItemV8.keyclass', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=12,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ITEMV8_KEYCLASS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=536,
)

_SECRETDATA.fields_by_name['keyReference'].message_type = _KEYREFERENCE
_ITEMV8.fields_by_name['secretData'].message_type = _SECRETDATA
_ITEMV8.fields_by_name['encryptedMetadata'].message_type = _ENCRYPTEDMETADATA
_ITEMV8.fields_by_name['keyclass'].enum_type = _ITEMV8_KEYCLASS
_ITEMV8_KEYCLASS.containing_type = _ITEMV8
DESCRIPTOR.message_types_by_name['KeyReference'] = _KEYREFERENCE
DESCRIPTOR.message_types_by_name['SecretData'] = _SECRETDATA
DESCRIPTOR.message_types_by_name['EncryptedMetadata'] = _ENCRYPTEDMETADATA
DESCRIPTOR.message_types_by_name['ItemV8'] = _ITEMV8

KeyReference = _reflection.GeneratedProtocolMessageType('KeyReference', (_message.Message,), dict(
  DESCRIPTOR = _KEYREFERENCE,
  __module__ = 'ItemV8_pb2'
  # @@protoc_insertion_point(class_scope:KeyReference)
  ))
_sym_db.RegisterMessage(KeyReference)

SecretData = _reflection.GeneratedProtocolMessageType('SecretData', (_message.Message,), dict(
  DESCRIPTOR = _SECRETDATA,
  __module__ = 'ItemV8_pb2'
  # @@protoc_insertion_point(class_scope:SecretData)
  ))
_sym_db.RegisterMessage(SecretData)

EncryptedMetadata = _reflection.GeneratedProtocolMessageType('EncryptedMetadata', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTEDMETADATA,
  __module__ = 'ItemV8_pb2'
  # @@protoc_insertion_point(class_scope:EncryptedMetadata)
  ))
_sym_db.RegisterMessage(EncryptedMetadata)

ItemV8 = _reflection.GeneratedProtocolMessageType('ItemV8', (_message.Message,), dict(
  DESCRIPTOR = _ITEMV8,
  __module__ = 'ItemV8_pb2'
  # @@protoc_insertion_point(class_scope:ItemV8)
  ))
_sym_db.RegisterMessage(ItemV8)


# @@protoc_insertion_point(module_scope)
